rabbit/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :tasks
  root 'tasks#index'
end

rabbit/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rabbit/app/models/category.rb
class Category < ApplicationRecord
  has_many :tasks
end

rabbit/app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category
end

rabbit/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

rabbit/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only: [:show, :edit, :update, :destroy]

  def index
    if params[:category].blank?
      @tasks = Task.all.order('created_at DESC')
    else
      @category_id = Category.find_by(name: params[:category])
      @tasks = Task.where(category_id: @category_id).order('created_at DESC')
    end

  end

  def show

  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to @task
    else
      render 'New'
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to @task
    else
      render 'Edit'
    end
  end

  def destroy
    @task.delete
    redirect_to root_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :description, :company, :url, :category_id)
  end

  def find_task
    @task = Task.find(params[:id])
  end
end

rabbit/app/helpers/application_helper.rb
module ApplicationHelper
end

rabbit/app/helpers/tasks_helper.rb
module TasksHelper
end

rabbit/app/views/layouts/application.html.haml
!!!
%html
%head
  %title TaskRabbit
  = csrf_meta_tags
  = csp_meta_tag

  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

%body
  %nav.navbar.navbar-default
    .container
      .navbar-brand= link_to 'TaskRabbit', root_path
      %ul.nav.navbar-nav
        %li= link_to 'All Tasks', root_path
        - Category.all.each do |category|
          %li= link_to category.name, tasks_path(category: category.name)

      = link_to 'New Task', new_task_path, class: 'navbar-text navbar-right navbar-link'

  .container
    .col-md-8.col-offset-2
      = yield