espn/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :messages do
    resources :comments
  end
  root 'messages#index'
end

espn/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

espn/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :message
  belongs_to :user
end

espn/app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  has_many :comments
end

espn/app/models/user.rb
class User < ApplicationRecord
  has_many :messages
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

espn/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

espn/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_message
  before_action :find_comment, only: [:edit, :update, :destroy]

  def create
    @comment = @message.comments.create(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      redirect_to message_path(@message)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      redirect_to message_path(@message)
    else
      render 'edit'
    end
  end

  def destroy
    @comment.destroy
    redirect_to message_path(@message)
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def find_message
    @message = Message.find(params[:message_id])
  end

  def find_comment
    @comment = @message.comments.find(params[:id])
  end
end

espn/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_message, only: [:show, :edit, :update, :destroy]

  def index
    @messages = Message.all.order("created_at DESC")
  end

  def show
  end

  def new
    @message = current_user.messages.build
  end

  def create
    @message = current_user.messages.build(message_params)

    if @message.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @message.update(message_params)
      redirect_to message_path
    else
      render 'edit'
    end
  end

  def destroy
    @message.destroy
    redirect_to root_path
  end

  private

  def message_params
    params.require(:message).permit(:title, :description)
  end

  def find_message
    @message = Message.find(params[:id])
  end
end

espn/app/helpers/application_helper.rb
module ApplicationHelper
end

espn/app/helpers/comments_helper.rb
module CommentsHelper
end

espn/app/helpers/messages_helper.rb
module MessagesHelper
end

espn/app/views/comments/_comment.html.erb
<div class="comment">
  <p class="comment-content"><%= comment.content %></p>
  <p class="comment-posted-by">By: <%= comment.user.email %> <%= time_ago_in_words(comment.created_at) %> ago</p>

  <div class="links">
    <% if user_signed_in? %>
      <% if comment.user_id == current_user.id %>
        <%= link_to 'Edit', edit_message_comment_path(comment.message, comment) %>
        <%= link_to 'Delete', message_comment_path(comment.message, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    <% end %>
  </div>
</div>

espn/app/views/comments/_form.html.erb
<%= simple_form_for ([@message, @message.comments.build]) do |f| %>
  <%= f.input :content, label: 'Comments' %>
  <%= f.button :submit, :class => 'btn btn-default' %>
<% end %>

espn/app/views/comments/edit.html.erb
<h1>Editing comment</h1>
<%= simple_form_for ([@message, @comment]) do |f| %>
  <%= f.input :content, label: 'Comments' %>
  <%= f.button :submit, :class => 'btn btn-default' %>
<% end %>

espn/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Espn</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <%= link_to 'ESPN FAN FORUM', root_path, class:"navbar-brand" %>
        </div>

        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to 'Log In', new_user_session_path %></li>
            <li><%= link_to 'Sign In', new_user_registration_path %></li>
          <% end %>
        </ul>
        <% if user_signed_in? %>
          <p><%= link_to 'Post Message', new_message_path, class: "navbar-text navbar-link" %></p>
        <% end %>
      </div>
    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>