broadway/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :plays do
    resources :reviews
  end
  root 'plays#index'
end

broadway/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

broadway/app/models/category.rb
class Category < ApplicationRecord
  has_many :plays
end

broadway/app/models/play.rb
class Play < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :reviews

  has_attached_file :play_img, :styles => { :play_index => "250x350>", :play_show => "325x475>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :play_img, content_type: /\Aimage\/.*\Z/
end

broadway/app/models/review.rb
class Review < ApplicationRecord
  belongs_to :play
  belongs_to :user
end

broadway/app/models/user.rb
class User < ApplicationRecord
  has_many :plays
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

broadway/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

broadway/app/controllers/plays_controller.rb
class PlaysController < ApplicationController
  before_action :find_play, only: [:show, :edit, :update, :destroy]
  before_action :find_categories, only: [:new, :edit]
  before_action :authenticate_user!, only: [:new, :edit]

  def index
    if params[:category].blank?
      @plays = Play.all.order('created_at DESC')
    else
      category_id = Category.find_by(name: params[:category]).id
      @plays = Play.where(:category_id => category_id).order('created_at DESC')
    end
  end

  def show
    if @play.reviews.blank?
      @average_review = 0
    else
      @average_review = @play.reviews.average(:rating).round(2)
    end
  end

  def new
    @play = current_user.plays.build
  end

  def create
    @play = current_user.plays.build(play_params)
    @play.category_id = params[:category_id]

    if @play.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @play.category_id = params[:category_id]

    if @play.update(play_params)
      redirect_to play_path(@play)
    else
      render 'edit'
    end
  end

  def destroy
    @play.destroy
    redirect_to root_path
  end

  private

  def play_params
    params.require(:play).permit(:title, :description, :director, :category_id, :play_img)
  end

  def find_play
    @play = Play.find(params[:id])
  end

  def find_categories
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end
end

broadway/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_play
  before_action :find_review, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.play_id = @play.id
    @review.user_id = current_user.id

    if @review.save
      redirect_to play_path(@play)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @review.update(review_params)
      redirect_to play_path(@play)
    else
      render 'edit'
    end
  end

  def destroy
    @review.destroy
    redirect_to play_path(@play)
  end

  private

  def find_play
    @play = Play.find(params[:play_id])
  end

  def review_params
    params.require(:review).permit(:rating, :comment)
  end

  def find_review
    @review = Review.find(params[:id])
  end
end

broadway/app/helpers/application_helper.rb
module ApplicationHelper
end

broadway/app/helpers/plays_helper.rb
module PlaysHelper
end

broadway/app/helpers/reviews_helper.rb
module ReviewsHelper
end

broadway/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Broadway</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" integrity="sha256-3dkvEK0WLHRJ7/Csr0BZjAWxERc5WH7bdeUya2aXxdU= sha512-+L4yy6FRcDGbXJ9mPG8MT/3UCDzwR9gPeyFNMCtInsol++5m3bk2bXWKdZjvybmohrAsn3Ua5x8gfLnbE1YkOg==" crossorigin="anonymous">
   <script
    src="https://code.jquery.com/jquery-3.4.1.js"
    integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
    crossorigin="anonymous">
  </script>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'jquery-raty', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <nav class="navbar navbar-expand">
    <div class="container">
      <div class="navbar-header">
        <%= link_to "Broadway", root_path, class: "navbar-brand" %>
      </div>
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Genres</a>
          <ul class="dropdown-menu navbar-inverse">
            <% Category.all.each do |category| %>
              <li class="<%= 'active' if params[:category] == category.name %>">
                <%= link_to category.name, plays_path(category: category.name), class: "link" %>
              </li>
            <% end %>
          </ul>
        </li>
        <li>
          <% if user_signed_in? %>
            <%= link_to "Add Play", new_play_path %>
          <% end %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <% if user_signed_in? %>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <span class="glyphicon glyphicon-log-out"></span>
              Sign Out
            <% end %>
          <% else %>
            <%= link_to new_user_registration_path do %>
              <span class="glyphicon glyphicon-user"></span>
              Sign Up
            <% end %>
            <%= link_to new_user_session_path do %>
              <span class="glyphicon glyphicon-log-in"></span>
              Log In
            <% end %>
          <% end %>
        </li>
      </ul>
    </div>
  </nav>

  <% if notice %>
    <p class="notice alert alert-info"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert alert-danger"><%= alert %></p>
  <% end %>

  <div class="container body-filled"l>
    <%= yield %>
  </div>
</body>
</html>

broadway/app/views/plays/_form.html.erb
<%= simple_form_for @play do |f| %>
  <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a Category") %>
  <%= f.file_field :play_img %>
  <%= f.input :title, label: 'Play title' %>
  <%= f.input :description, label: 'Story' %>
  <%= f.input :director %>
  <%= f.button :submit, :class => 'btn btn-default' %>
<% end %>

broadway/app/views/plays/edit.html.erb
<div class="col-md-10 col-md-offset-1">
  <div class="new-play-form">
    <h1>Editing Broadway Play</h1>

    <%= simple_form_for @play, html: { multipart: true } do |f| %>
      <%= f.file_field :play_img %>
      <%= f.select :category_id, @categories %>
      <%= f.input :title, label: 'Play title' %>
      <%= f.input :description, label: 'Story' %>
      <%= f.input :director %>
      <%= f.button :submit, :class => 'btn btn-default' %>
    <% end %>
  </div>
</div>

broadway/app/views/plays/index.html.erb
<h1 class="current-category"><%= params[:category] %> </h1>

<% if @plays.count == 0 %>
  <h3>There are no plays under this category</h3>
<% else %>
  <div class="row">
    <% @plays.each do |play| %>
      <div class="col-md-3">
        <a href="/plays/<%= play.id %>">
          <%= image_tag play.play_img.url(:play_index), class: "play" %>
        </a>
      </div>
    <% end %>
  </div>
<% end %>

broadway/app/views/plays/new.html.erb
<div class="col-md-10 col-md-offset-1">
  <div class="new-play-form">
    <h1>New Broadway Play</h1>

    <%= render 'form' %>
  </div>
</div>

broadway/app/views/plays/show.html.erb
<div class="row">
  <div class="col-md-4">
    <%= image_tag @play.play_img.url(:play_show), class: "play-show" %>
  </div>

  <div class="col-md-7">
    <div class="play-info">
      <h2 class="play-title"><%= @play.title %></h2>
      <h3 class="play-director"><span><em>From: </em></span><%= @play.director %></h3>
      <h4><%= @play.category.name %></h4>
      <h4 class="avg-rating">Average Rating</h4>
      <div class="average-review-rating" data-score=<%= @average_review %>></div>
      <span class="number-of-reviews"><em>From</em> <%= @play.reviews.count %> reviews </span>
      <p class="play-desc"><%= @play.description %></p>
    </div>
  </div>
</div>

<div class="links btn-group">
  <% if user_signed_in? %>
    <% if @play.user_id == current_user.id %>
      <%= link_to 'Edit', edit_play_path(@play), class: "btn btn-custom" %>
      <%= link_to 'Delete', play_path(@play), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-custom" %>
    <% end %>
  <% end %>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="reviews">
      <h1> Reviews </h1>
      <%= render @play.reviews %>
      <div>
        <%= link_to 'Add Reviews', new_play_review_path(@play), class: "btn-custom" %>
      </div>
    </div>
  </div>
</div>

<script>
  $('.review-rating').raty({
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });
</script>

<script>
  $('.average-review-rating').raty({
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });
</script>