project_management/config/routes.rb
Rails.application.routes.draw do
  root "projects#index"
  resources :projects do
    resources :tasks do
      member do
        patch :complete
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

project_management/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

project_management/app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks
end

project_management/app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project

  def completed?
    !completed_at.blank?
  end
end

project_management/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

project_management/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description)
    end
end

project_management/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_project
  before_action :set_task, except: [:create]

  def create
    @task = @project.tasks.create(task_params)
    redirect_to @project
  end

  def destroy
    if @task.destroy
      flash[:success] = 'Task deleted.'
    else
      flash[:success] = "Task couldn't be deleted."
    end
    redirect_to @project
  end

  def complete
    @task.update_attribute(:completed_at, Time.now)
    redirect_to @project, notice: 'Task completed.'
  end

  private

  def task_params
    params[:task].permit(:content)
  end

  def find_project
    @project = Project.find(params[:project_id])
  end

  def set_task
    @task = @project.tasks.find(params[:id])
  end
end

project_management/app/helpers/application_helper.rb
module ApplicationHelper
end

project_management/app/helpers/projects_helper.rb
module ProjectsHelper
end

project_management/app/helpers/tasks_helper.rb
module TasksHelper
end

project_management/app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

project_management/app/views/projects/edit.html.erb
<h1 class="todo_list_title">Editing Project</h1>

<div class="forms">
  <%= render 'form', project: @project %>
  </div>

<div class="links">
  <%= link_to 'Cancel', projects_path %>
</div>

project_management/app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<% @projects.each do |project| %>
  <div class="index_row clearfix">
    <h2 class="todo_list_title"><%= link_to project.title, project %></h2>
    <p class="todo_list_sub_title"><%= project.description %></p>
  </div>
<% end %>

<div class="links">
  <%= link_to 'New Project', new_project_path %>
</div>

project_management/app/views/projects/new.html.erb
<h1 class="todo_list_title">New Project</h1>

<div class="forms">
  <%= render 'form', project: @project %>
</div>

<div class="links">
  <%= link_to 'Back', projects_path %>
</div>

project_management/app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<h2 class="todo_list_title"><%= @project.title %></h2>
<p class="todo_list_subtitle"><%= @project.description %></p>

<div id="todo_items_wrapper">
  <%= render @project.tasks %>
  <div id="form">
    <%= render "tasks/form" %>
  </div>
</div>

<div class="links">
  <%= link_to 'Edit', edit_project_path(@project) %> |
  <%= link_to 'Back', projects_path %> |
  <%= link_to 'Delete', project_path(@project), method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

project_management/app/views/tasks/_form.html.erb
<%= form_for ([@project, @project.tasks.build]) do |f| %>
  <%= f.text_field :content, placeholder: "New Task" %>
  <%= f.submit %>
<% end %>

project_management/app/views/tasks/_task.html.erb
<div class="row clearfix">
  <% if task.completed? %>
    <div class="complete">
      <%= link_to complete_project_task_path(@project, task.id), method: :patch  do %>
        <i style="opacity: 0.4;" class="fa fa-check"></i>
      <% end %>
    </div>
    <div class="todo_item">
      <p style="opacity: 0.4;"><strike><%= task.content %></strike></p>
    </div>
    <div class="trash">
      <%= link_to project_task_path(@project, task.id), method: :delete, data: { confirm: 'Are you sure?' } do %>
        <i class="fa fa-trash"></i>
      <% end %>
    </div>
  <% else %>
    <div class="complete">
      <%= link_to complete_project_task_path(@project, task.id), method: :patch  do %>
        <i class="fa fa-check"></i>
      <% end %>
    </div>
    <div class="todo_item">
      <p><%= task.content %></p>
    </div>
    <div class="trash">
      <%= link_to project_task_path(@project, task.id), method: :delete, data: { confirm: 'Are you sure?' } do %>
        <i class="fa fa-trash"></i>
      <% end %>
    </div>
  <% end %>
</div>